### ISSUE TITLE
Dependencies are not decoupled

### ISSUE THREAD

**Issue by andreapiso** [veritas-toolkit/diagnosis-tool#1]
Dependencies right now are all loaded upfront, rather than when necessary. 

For example, If i wanted to calculate Fairness, but not display it, i should not have to install `ipywidgets` or similar tools. Otherwise, it will mean from now on all our productions projects will need to ship with extra dependencies even if they do not need them. This would introduce a lot of bloat and would not be acceptable in a production setting. 

As a pratiical reproducible example, loading model container from source, produces this:

```
from veritastool.model.model_container import ModelContainer
```
```
from ..fairness.fairness import Fairness
from .credit_scoring import CreditScoring
from .fairness import Fairness
import ipywidgets as widgets
```
Which will in turn produce an error if all the jupyter stack is not installed (which in our case it never is, in a production image)

**Comment by mas-veritas2** [comment]
noted. we will move import closer to the actual function in ver 2.0.
