### ISSUE TITLE
Performance and Fairness Metrics Results Questions

### ISSUE THREAD

**Issue by LIFENGZI1015** [veritas-toolkit/diagnosis-tool#4]
I try to get performance and fairness metrics results but have two questions:

**In performance_metrics.py line 211:**
`self.result['perf_metric_values'][j] = (self.result['perf_metric_values'][j][-1],  2*np.std(self.result['perf_metric_values'][j]))`

**Q1:** why we take the last item [-1] from the list ['perf_metric_values'][j] as the metric value? Shouldn't this be the mean value? 

**In fairness_metrics.py line 243:**
`self.result[i]["fair_metric_values"][j] = self.result[i]['fair_metric_values'][j][-1] + (2*np.std([a_tuple[0] for a_tuple in self.result[i]["fair_metric_values"][j]]),)`

**Q2:** can you explain the results here? for each fairness metric, I have three values:

{'country_code': {'disparate_impact': (0.9899166435069041,
   0.9313824419778002,
   0.010717541771964288),....}

According to the document, I should get "a dictionary with keys as the fairness metric name and values as the metric value together with confidence interval".

**Comment by mas-veritas2** [comment]
Q1: [-1] refers to the 1st round of results. the target output is [metric_value, confidence_range]. confidence_range is derived by 50-round bootstrapping (1st run + 49 runs later)

Q2: (metric_value, privileged_metric_value, confidence_range). "privileged_metric_value" refers to corresponding performance value of privileged group in a fairness metric. e.g. in disparate_impact, DI = Pr(Y=1|D = unprivileged) / Pr(Y=1|D = privileged), privileged_metric_value is the denominator. it's useful for computing fairness metric threshold.
